GET http://localhost:5000/product

###
POST http://localhost:5000/product/products
    Content-Type: application/json


    {
        "productName": "television",
        "cost": 2000
    }



###

DELETE http://localhost:5000/product/products/ 1698
       Content-Type: application/json

###
PATCH  http://localhost:5000/product/products/4196
       Content-Type: application/json

       {
        "stockStatus":"out-of-stock"
       }
