GET http://localhost:5000/product/products/1698

###
POST http://localhost:5000/product/products
    Content-Type: application/json

{
    "productName": "radio",
    
    "cost": "500"
}

###

DELETE http://localhost:5000/product/products/ 1698
       Content-Type: application/json

###
PATCH  http://localhost:5000/product/products/6814
       Content-Type: application/json

       {
        "stockStatus":"out-of-stock"
       }
